source 'https://cdn.cocoapods.org/'
$projectName = 'ShifuExample'
$version = '15.0'
platform :ios, $version

use_frameworks!
inhibit_all_warnings!

target $projectName do
  pod 'Shifu', :path => '../'
end


post_install do |installer|
  framework = installer.pods_project.frameworks_group["iOS"]["MobileCoreServices.framework"]
    framework.referrers.each do |ref|
        if ref.isa == "PBXBuildFile"
            ref.remove_from_project
        end
    end
  framework.remove_from_project
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $version
      if config.name == "Debug"
        xcconfig_path = config.base_configuration_reference.real_path
        File.open(xcconfig_path, "a") {|file| file.puts "OTHER_LDFLAGS[sdk=iphonesimulator*] = $(inherited) -Xlinker -interposable -undefined dynamic_lookup"}
      end
    end
  end
end

