use_frameworks!

target 'Shifu_Example' do
  pod 'Shifu', :path => '../'
  pod 'FMDB'
end



# post_install do |installer|
#     installer.pods_project.build_configurations.each do |config|
#         if config.name == 'Release'
#           config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
#         else
#           config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
#         end
#     end
# end
